### ISSUE TITLE
buid server with flutter socket plugin

### ISSUE THREAD

**Issue by pretech86** [waitwalker/flutter_socket_plugin#13]
is is possible to build server side by flutter and flutter_socket_plugin like the client or it still under updated ?

**Comment by waitwalker** [comment]
I will write a socket server example in dart language recently. flutter_socket_plugin is a simple socket client. I don't know what function you want to achieve with socket.

**Comment by pretech86** [comment]
i just ask because i'm not familar with objective c , i familar with dart and flutter and i want all project with flutter , client and server 
just to know what happened and to solve any problem

**Comment by waitwalker** [comment]
ok.I will write a server-side example with dart in the near future. I hope it will be helpful to you.

**Comment by pretech86** [comment]
thanks a lot

**Comment by waitwalker** [comment]
The problem has been solved, and the demo code of the server has been added.
