### ISSUE TITLE
can you provide the code for server socket app

### ISSUE THREAD

**Issue by mailnowpub** [waitwalker/flutter_socket_plugin#2]
In example section you displayed two different application first one is server and other two are clients but you only provided the code for client app please provide the code for server app also.. thankyou

**Comment by waitwalker** [comment]
Please leave your email.

**Comment by mailnowpub** [comment]
shivanagarwal067@gmail.com

**Comment by waitwalker** [comment]
> [shivanagarwal067@gmail.com](mailto:shivanagarwal067@gmail.com)

Sent.

**Comment by waitwalker** [comment]
> > [shivanagarwal067@gmail.com](mailto:shivanagarwal067@gmail.com)
> 
> Sent.
shivanagarwal067@gmail.com
550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces.

**Comment by mailnowpub** [comment]
sorry, spelling error. email: shivamagarwal067@gmail.com

**Comment by waitwalker** [comment]
> sorry, spelling error. email: [shivamagarwal067@gmail.com](mailto:shivamagarwal067@gmail.com)

Sent.
