### ISSUE TITLE
Can you check the error what i get please

### ISSUE THREAD

**Issue by prabhunath111** [waitwalker/flutter_socket_plugin#4]
I/.example.socke(17490): ProcessProfilingInfo new_methods=394 is saved saved_to_disk=1 resolve_classes_delay=8000
E/MethodChannel#flutter_socket_plugin(17490): Failed to handle method call
E/MethodChannel#flutter_socket_plugin(17490): java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.xuhao.didi.socket.client.sdk.client.connection.IConnectionManager.isConnect()' on a null object reference
E/MethodChannel#flutter_socket_plugin(17490): 	at cn.waitwalker.flutter_socket_plugin.FlutterSocket.tryConnect(FlutterSocket.java:107)
E/MethodChannel#flutter_socket_plugin(17490): 	at cn.waitwalker.flutter_socket_plugin.FlutterSocketPlugin.onMethodCall(FlutterSocketPlugin.java:58)
E/MethodChannel#flutter_socket_plugin(17490): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_socket_plugin(17490): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_socket_plugin(17490): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_socket_plugin(17490): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_socket_plugin(17490): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_socket_plugin(17490): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter_socket_plugin(17490): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#flutter_socket_plugin(17490): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_socket_plugin(17490): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter_socket_plugin(17490): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (17490): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'boolean com.xuhao.didi.socket.client.sdk.client.connection.IConnectionManager.isConnect()' on a null object reference, null)
E/flutter (17490): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (17490): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (17490): <asynchronous suspension>
E/flutter (17490): #2      FlutterSocket.tryConnect (package:flutter_socket_plugin/flutter_socket.dart:121:20)
E/flutter (17490): <asynchronous suspension>
E/flutter (17490): #3      _HomePageState.build.<anonymous closure> (package:socket/main.dart:135:35)
E/flutter (17490): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (17490): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (17490): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (17490): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (17490): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (17490): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (17490): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (17490): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (17490): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (17490): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (17490): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (17490): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (17490): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (17490): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (17490): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (17490): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (17490): #20     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (17490): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (17490):

**Comment by waitwalker** [comment]
E/flutter (17490): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'boolean com.xuhao.didi.socket.client.sdk.client.connection.IConnectionManager.isConnect()' on a null object reference, null)

**Comment by expertmars** [comment]
how to solve? did you found any solutions?

**Comment by waitwalker** [comment]
The problem has been solved, and the demo code of the server has been added.
