### ISSUE TITLE
Server Socket

### ISSUE THREAD

**Issue by ernestodgr** [waitwalker/flutter_socket_plugin#5]
Hello how are you doing? Is the application that works as a server made in flutter? Because I need to do one like that. Thank you
ernestodavid.gr@gmail.com

**Comment by waitwalker** [comment]
Sent.

**Comment by pretech86** [comment]
@ernestodgr kindly can you send the server code to me karemzky@gmail.com

**Comment by waitwalker** [comment]
sent.
