### ISSUE TITLE
errorListener

### ISSUE THREAD

**Issue by JackZhangdaye** [waitwalker/flutter_socket_plugin#8]
I/flutter (10967): 错误回调 data:com.xuhao.didi.core.exceptions.ReadException: Need to follow the transmission protocol.
I/flutter (10967): Please check the client/server code.
I/flutter (10967): According to the packet header data in the transport protocol, the package length is 2065851493 Bytes.
I/flutter (10967): You need check your <ReaderProtocol> definition

**Comment by JackZhangdaye** [comment]
服务端是安卓手机，传输数据格式是gb2312，局域网。字符串应该是可以的，用flutter自带的socket是没有问题的，这个错误应该怎么解决呢

**Comment by waitwalker** [comment]
> 服务端是安卓手机，传输数据格式是gb2312，局域网。字符串应该是可以的，用flutter自带的socket是没有问题的，这个错误应该怎么解决呢

你自己看看怎么解决吧
