### ISSUE TITLE
server socket

### ISSUE THREAD

**Issue by pretech86** [waitwalker/flutter_socket_plugin#9]
thanks for the great tool , kindly can you send to me the server socket code please , which you make for connect to the client 

hope you send it karemzky@gmail.com

**Comment by waitwalker** [comment]
> thanks for the great tool , kindly can you send to me the server socket code please , which you make for connect to the client
> 
> hope you send it [karemzky@gmail.com](mailto:karemzky@gmail.com)

sent.
